### ISSUE TITLE
Формирование списка вопросов по фундаментальному файлу

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#1]

**Comment by TheShenk** [comment]
1. Почему для листов "К03, Т03" и "К04, Т04" нет правой таблицы?
2. Что означают разные цвета левой таблицы на листах К0X, Т0X? Это разделения на окна в соответствии с листом "Пояснения"?

**Comment by TheShenk** [comment]
3. Что такое каналы? Где они выбираются? Как изменяется поведение программы? Нужно настраивать параметры для каждого канала?
4. Что такое "определяется датчиком"? Его нужно отображать?

**Comment by vbezuprechnaya** [comment]
5. На листе "К01, Т01" в первом пункте при выборе параметров 1 или 2 идёт ссылка на лист "К02, Т02" к пункту **2.**, но он не прописан. 

6. Так же в первом пункте при выборе 3 нужно добавить массив с данными о 125 параметре. Какой переход выполняется после этого действия?

7. В пункте 3 на этом же листе не прописаны действия для всех типов расходомера, кроме 12. Какие действия выполняются дальше?

8.  в пункте 5.3 в комментарии написано записать в ячейку "0", а введённый параметр применить позже при выполнении пункта 10. Зачем записывать "0" в ячейку, если можно просто сохранить нужные данные и проверить их в нужных окнах?

**Comment by AlexandrovichValeria** [comment]
9. Что делать, если пользователь выбирает не применять АДС97, или если все адаптеры уже использованы?
