### ISSUE TITLE
Сохранение пустой базы данных

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#107]
Сейчас при открытии программы и сохранении пустых настроек - NullReferenceException. Необходимо сохранение минимально возможной базы данных, которая без ошибок откроется в Конфигураторе. Или хотя бы отображение alert'а пользователю.

**Comment by PodoprigoraIvan** [comment]
@TheShenk Кажется на ветке 94 это проблема была решена и сейчас её уже нет
