### ISSUE TITLE
Привязка вида первого окна настроек трубопровода к типу датчика

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#122]
У первого окна настроек трубопровода есть зависимость от вида теплоносителя.

![Image](https://user-images.githubusercontent.com/34752373/239687456-a6df1e6d-575d-4e27-9d70-79d4cc1b7656.png)

**Comment by vbezuprechnaya** [comment]
Эту проблему поправили в #130
