### ISSUE TITLE
Исправление верхнего предела номиального диапазона измерения датчика расхода

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#136]
Кажется, в этом параметре всегда сохраняется значение по умолчанию.

![Image](https://user-images.githubusercontent.com/34752373/239686144-5a122856-6572-4182-acb2-139b01a9ff62.png)

**Comment by AlexandrovichValeria** [comment]
проблема была исправлена в пулл-реквесте #132
