### ISSUE TITLE
Возвращение нижнего предела измерений на второе окно настроек трубопровода

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#148]
При выполнении #130 убрали эту настройку из окна. Но, судя по фундментальному файлу, нужно было сделать поле неизменяемым со значением "0". В результате не понятно откуда берется значение при подтверждении на третьем окне настроек трубопровода.

![Image](https://user-images.githubusercontent.com/34752373/242080702-bf26eb56-bf02-4888-883a-418c30aae6b8.png)

**Comment by AlexandrovichValeria** [comment]
в #130 убирали другой параметр (032н02 а не 034н02). Параметр 034н02 можно менять только при определенных настройках датчика (как и указано в фундаментальном файле). В противном случае возможность редактирования не представляется и значение равно 0
