### ISSUE TITLE
Разработка класса-окна для общего вида приложения

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#32]
Данная задача предполагает разработку окна, состоящего и трех частей:
1. Верхняя панель - меню с сохранением файла
2. Часть для содержания
3. Место для расположения дугих форм - самая важная часть задачи, выяснение того, как переключать окна, не создавая новые окна, а располагая их в этом части.
4. Желательно, чтобы при развороте на весь экран, окно сохраняло свою структуру

![Image](https://user-images.githubusercontent.com/34752373/231078442-1e04e01e-35b5-47a7-9716-67d7ce282127.png)

**Comment by PodoprigoraIvan** [comment]
![Image](https://user-images.githubusercontent.com/57725067/231491951-2db73a8e-65ae-4cd8-a112-b650828ba1c5.png)
