### ISSUE TITLE
Разработка компонента ввода используемых потребителей и трубопроводов

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#33]
Необходимо разрабтать компонент для ввода трубопроводов и потребителей:

![Image](https://user-images.githubusercontent.com/34752373/231078590-039093ef-3f19-4277-9717-020737c77276.png)

Требования к нему:

1. Настраиваемое число checkbox-ов
2. Настраиваемый текст имени (т или п)
3. Значение, которое он возвращает (например, с сигналом) - строка из 0 и 1

**Comment by AlexandrovichValeria** [comment]
![Image](https://user-images.githubusercontent.com/71718459/232333910-6a7752bc-b295-4fac-b5b1-62bdf5c256f4.PNG)



![Image](https://user-images.githubusercontent.com/71718459/232333915-2e1b7380-3330-4d57-a613-97c78ea4a909.PNG)



![Image](https://user-images.githubusercontent.com/71718459/232333919-6230b0b2-62ef-44ba-93ce-0a2af3d1b55c.PNG)
