### ISSUE TITLE
Разработка окна выбора типа вычислителя

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#35]
Необходимо разработать окно выбора вычислителя. При этом возникает вопрос, нужно ли его реализовывать как самостоятельное окно или в "общем" интерфейсе. Возможно, что для такого небольшого окна реализация в общем интерфейсе будет только мешать.

![Image](https://user-images.githubusercontent.com/34752373/231528462-9cdc7ad0-2b32-4468-bf20-8b219f8beaf3.png)

**Comment by PodoprigoraIvan** [comment]
![Image](https://user-images.githubusercontent.com/57725067/232248460-6169f60b-9464-47ce-b9fa-8bcc99470118.jpg)



![Image](https://user-images.githubusercontent.com/57725067/232248464-fd02286f-87f3-4a2c-bee5-a82f74c9635c.jpg)
