### ISSUE TITLE
Разработка окна ввода параметров потребителей

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#36]
Необходимо разработать страницу для ввода параметров потребителей.

![Image](https://user-images.githubusercontent.com/34752373/231528826-63bc12da-c895-4dd9-93b1-7dfeb9d92b6b.png)

**Comment by PodoprigoraIvan** [comment]
![Image](https://user-images.githubusercontent.com/57725067/231888511-2d11aa95-9cc2-421a-9daf-a46e87de45f6.jpg)
