### ISSUE TITLE
Разработка окна выбора теплоносителя

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#43]
Необходимо разработать окно выбора теплоносителя.

![Image](https://user-images.githubusercontent.com/34752373/232401004-54511809-00a1-49dd-b579-9a7f67cce456.png)

При этом обратите внимание на комментарии на макете, некоторые части видны/доступны для ввода только при выборе определенных значениях теплоносителя.

**Comment by AlexandrovichValeria** [comment]
![Image](https://user-images.githubusercontent.com/71718459/233793315-7a364973-d88a-4954-b301-857a83b1ffda.PNG)


![Image](https://user-images.githubusercontent.com/71718459/233793321-6cf05e04-0f94-48a0-86e9-dd47c4c468a5.PNG)
![Image](https://user-images.githubusercontent.com/71718459/233793320-402e07db-d292-4ead-9ff5-d3c33a16d54c.PNG)
