### ISSUE TITLE
Изменение вариантов номера схемы учета на окне ввода параметров потребителей

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#58]
Необходимо изменить варианты номера схемы учета на читаемые.

![Image](https://user-images.githubusercontent.com/34752373/234185129-3ce866b7-ec9d-4dcd-9a85-d4b521abfe6b.png)

![Image](https://user-images.githubusercontent.com/34752373/234098086-52d49514-19de-4345-830c-f46a9746004d.png)

**Comment by PodoprigoraIvan** [comment]
@TheShenk На данный момент я сделал такой элемент для выбора схемы учета (LaTeX рендерится с помощью дополнительного пакета WPFmath). Какие есть предложения/замечания по внешнему виду?


![Image](https://user-images.githubusercontent.com/57725067/234963795-79faea88-d06f-440c-9d55-aa4ff35acebb.png)



![Image](https://user-images.githubusercontent.com/57725067/234963962-ef579975-9979-4794-ab09-370db9b72d74.png)

**Comment by TheShenk** [comment]
@PodoprigoraIvan Получилось очень хорошо, спасибо.
1. Не особо важно, но как оно будет смотреться, если шрифт "Схема 5" в выборе уменьшить до стандартного? Вполне возможно, что рядом с такими формулами увеличенный шрифт (который сейчас) подойдет лучше, поэтому интересует ваше мнение.
2. Необходимы ли со стороны пользователя действия для установки пакета? Или он "встраивается" при сборке?

**Comment by PodoprigoraIvan** [comment]
@TheShenk 
1. Мне кажется лучше выглядит с большим шрифтом.
2. От пользователя дополнительных действий не требуется, при установке будут просто два .dll файла, связанных с этим пакетом, лежать рядом с .exe

**Comment by TheShenk** [comment]
@PodoprigoraIvan Ок, тогда жду pull request.
