### ISSUE TITLE
Изменение логики выбора типа вычислителя

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#59]
1. Выбор типа вычислителя - отдельным окном при запуске
2. Для изменения - файл->создать и обнуление всего

**Comment by PodoprigoraIvan** [comment]
![Image](https://user-images.githubusercontent.com/57725067/234517005-9b5d5217-5ff9-4443-9e90-f1d8130870ab.png)

**Comment by PodoprigoraIvan** [comment]
![Image](https://user-images.githubusercontent.com/57725067/234517301-f01f7c89-55bb-4588-8476-3158f22d6534.png)
