### ISSUE TITLE
Разработка второго окна ввода параметров трубопроводов

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#60]
Необходимо разработать окно №2 для ввода параметров трубопровода.

![Image](https://user-images.githubusercontent.com/34752373/234187808-59b7a11d-eb8a-4daa-b66c-ba3c033c3488.png)

Требования:
1. Значение нижнего порога - из предыдущего окна, значение по умолчанию - параметр 034н02. При этом значение сохраняется в 115н01
2. По умолчанию - checkbox установлен в true и поля ввода заблокированы
3. При снятия checkbox'а поля становятся доступны для изменения

**Comment by AlexandrovichValeria** [comment]
![Image](https://user-images.githubusercontent.com/71718459/235306313-79e8146b-d339-48c5-adb8-bb262df46f5a.PNG)



![Image](https://user-images.githubusercontent.com/71718459/235306315-4bfef5d7-7b96-4376-bfc8-c871e6adc513.PNG)

**Comment by AlexandrovichValeria** [comment]
![Image](https://user-images.githubusercontent.com/71718459/235368031-c8513f96-3f18-4750-ae12-8cf7be99aa86.PNG)



![Image](https://user-images.githubusercontent.com/71718459/235368035-98021756-12b5-4db2-bfd4-183b3bcb37b9.PNG)
