### ISSUE TITLE
Изменение окна выбора теплоносителя после обновления макета

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#69]
Необходимо обновить окно теплоносителя до такого состояния:

![Image](https://user-images.githubusercontent.com/34752373/235848380-38030d1c-bd15-432c-b1a4-63c81fe6901c.png)

То есть:
1. Изменить расположение элементов
2. Изменить варианты выбора
3. Добавить таблицу для ввода 125 параметра, которая появляется при выборе соответсвующих теплоносителей
4. Сделать окно адаптивным

**Comment by AlexandrovichValeria** [comment]
![Image](https://user-images.githubusercontent.com/71718459/236630704-1d5701bb-5e81-4038-8ac9-c22bf29aa550.PNG)



![Image](https://user-images.githubusercontent.com/71718459/236630706-705876d7-712a-4b52-b425-d7ec588fe14e.PNG)
![Image](https://user-images.githubusercontent.com/71718459/236630707-b8bd5207-f80c-43b5-b054-4f245fa83c16.PNG)

**Comment by AlexandrovichValeria** [comment]
![Image](https://user-images.githubusercontent.com/71718459/236674696-2e866450-e6c9-48c6-9372-bd5ca5ccc881.PNG)
