### ISSUE TITLE
Определение версии .NET

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#7]
Цель данной задачи - определиться с версией .NET для приложения. Необходимо проверить, имеется ли у них обратная совместимость с .NET4.0, какие различия между версиями и понять, какие могут быть использованы. 
Результат - обновление версии .NET в репозитории. На данный момент используется 3.1

**Comment by PodoprigoraIvan** [comment]
Именования версий .NET поначалу немного сбивают с толку. .NET Framework 4.0, про совместимость с которым идет речь является старой версией 2010 года, а .NET Core (более поздние версии без Core в названии) - это кроссплатформенный преемник .NET Framework. Совместимости между ними нет, как я понял, но заказчик сказал, что для нашего проекта совместимая версия .NET это не требование, а пожелание/рекомендация. Между ними есть отличие в версии языка C# (в .NET Framework более старая версия). С учетом вышесказанного можно перейти на последнюю версию .NET Framework (4.8), т.к. есть обратная совместимость с 4.0, или же можно перейти на новую версию .NET, при условии что совместимость с Framework 4.0 не критична, но я не думаю, что нам сильно необходимы фичи из новых версий C#.
@TheShenk Я склоняюсь к версии .NET Framework 4.8, её и выбираем?

**Comment by TheShenk** [comment]
@PodoprigoraIvan Да, согласен, что лучше остановиться на 4.8. Тогда для завершения задачи нужно еще обновить версию в репозитории.
