### ISSUE TITLE
Адаптивный дизайн для окна общесистемных настроек

### ISSUE THREAD

**Issue by TheShenk** [frostsergei/MSE-2023-msm-industrial_design-19#95]
Для общесистемных настроек есть не критичные, но важные проблемы с адаптируемостью. Подробнее здесь: https://github.com/moevm/MSE-2023-msm-industrial_design-19/pull/63

**Comment by AlexandrovichValeria** [comment]
![Image](https://github.com/moevm/MSE-2023-msm-industrial_design-19/assets/71718459/2a61fbd3-3a34-426f-9e8d-3a7b710cbfce)
